### ISSUE TITLE
Magic behind the scenes

### ISSUE THREAD

**Issue by tyler-harpool** [timlabs/uscode#1]
Can you share the scripts that are you are using behind the scenes?

**Comment by smithtim** [comment]
Thank you for your interest, and my apologies for the delayed response.

There is a script, but it needs clean-up and updating.  Was there something in particular you wanted it for?

**Comment by tharpooljha** [comment]
We are trying to use it in this project. https://github.com/federal-courts-software-factory/uscmobile

**Comment by smithtim** [comment]
Neat, let me see what I can do.

**Comment by smithtim** [comment]
I have released the script under the AGPL.  Good luck with your project.
